name: Monitor New Links

on:
  schedule:
    - cron: "*/15 * * * *"  # Executar a cada 15 minutos
  workflow_dispatch: # Permite executar manualmente, se necessário.

jobs:
  monitor-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dropbox  # Instala a biblioteca Dropbox

    - name: Run Monitoring Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}  # Passa o token do Dropbox como variável de ambiente
      run: python3 script.py
