name: Monitor New Links

on:
  schedule:
    - cron: "*/15 * * * *"  # Executar a cada 15 minutos
  workflow_dispatch: # Permite executar manualmente, se necessário.

jobs:
  monitor-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Dependencies (Without Cache)
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Run Monitoring Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}  # Aqui o token do Dropbox
      run: python3 ntc_avr.py

