name: Send Emails on New Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"  # Executar a cada 15 minutos

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step to check if the cache is already updated and needs to be restored
    - name: Restore Cache if Available
      id: cache-restore
      uses: actions/cache@v3
      with:
        path: seen_links_ntc.txt
        key: ${{ runner.os }}-seen-links-cache-ntc-${{ hashFiles('seen_links_ntc.txt') }}
        restore-keys: |
          ${{ runner.os }}-seen-links-cache-ntc-

    - name: Save hash of seen_links_ntc.txt before running the script
      id: hash-before
      run: |
        if [ -f seen_links_ntc.txt ]; then
          hash_before=$(sha256sum seen_links_ntc.txt | cut -d ' ' -f 1)
          echo "Hash before: $hash_before"
          echo "HASH_BEFORE=$hash_before" >> $GITHUB_ENV
        else
          echo "HASH_BEFORE=" >> $GITHUB_ENV
        fi

    - name: Run the Python Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python3 ntc_avr.py

    - name: Save hash of seen_links_ntc.txt after running the script
      id: hash-after
      run: |
        if [ -f seen_links_ntc.txt ]; then
          hash_after=$(sha256sum seen_links_ntc.txt | cut -d ' ' -f 1)
          echo "Hash after: $hash_after"
          echo "HASH_AFTER=$hash_after" >> $GITHUB_ENV
        else
          echo "HASH_AFTER=" >> $GITHUB_ENV
        fi

    - name: Check if seen_links_ntc.txt was modified
      run: |
        if [ "$HASH_BEFORE" != "$HASH_AFTER" ]; then
          echo "File seen_links_ntc.txt was modified."
        else
          echo "File not modified."
        fi

    # Save cache only if the file was modified
    - name: Save Cache if Links Changed
      if: ${{ env.HASH_BEFORE != env.HASH_AFTER }}
      uses: actions/cache@v3
      with:
        path: seen_links_ntc.txt
        key: ${{ runner.os }}-seen-links-cache-ntc-${{ env.HASH_AFTER }}  # Use hash after modification
        restore-keys: |
          ${{ runner.os }}-seen-links-cache-ntc-

    - name: Final Check and Cache Status
      run: |
        echo "Cache Key Before: ${{ steps.cache-restore.outputs.cache-key }}"
        echo "New Cache Key After: ${{ env.HASH_AFTER }}"
        if [ -f seen_links_ntc.txt ]; then
          echo "Cache file content after script execution:"
          cat seen_links_ntc.txt
        else
          echo "No cache file found after script execution."
        fi
